### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by brandonefields** [learn-co-curriculum/phase-0-pac-2-selection-with-conditionals#1]
JavaScript includes three structures for implementing code conditionally: if statements, switch statements, and ternary expressions. In this lesson, we will learn how to contruct if statements.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials to correct the error.

Thanks for contributing to the Flatiron School curriculum 💙
