### ISSUE TITLE
Embedded REPLs in this Lesson

### ISSUE THREAD

**Issue by genevievesuder** [learn-co-curriculum/phase-0-pac-2-selection-with-conditionals#7]
### Canvas Link

https://learning.flatironschool.com/courses/6106/pages/selection-with-conditionals-the-if-statement?module_item_id=471003

### Concern

I am not seeing a code window, only the console window. Code is not shown or explained, only console.log result is shown.

### Suggested Changes

Add in REPL code window

**Comment by jlboba** [comment]
In relation to the [issue on switch statements](https://github.com/learn-co-curriculum/phase-0-pac-2-switch-statements/issues/4), this has been fixed as well with pull request #6 

Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

Again, we appreciate your support! 💙
